### ISSUE TITLE
Error running inference

### ISSUE THREAD

**Issue by MammalBubble** [abhishekdbihani/MudrockNet#1]
Tried to run inference.py in virtual env using python 3.6 with tensorflow 1.15. Author`s model checkpoints were also used. 
Got the error: "tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_109}} Number of ways to split should evenly divide the split dimension, but got split_dim 2 (size = 4) and num_split 3"

P.S. Big thanks to the author, can`t wait to use this model

**Comment by abhishekdbihani** [comment]
Hi, sorry for the late response. This error is occasionally seen in some examples due to image dimension mismatch. Please try to run the model for other test images.
